remote_theme: niklasbuschmann/contrast

title: "David Golding"
author: "David Golding"
description: "I’m a PhD candidate in Education and Social Justice at Lancaster University. My research looks at decolonial theory, development, international education, governmentality, neoliberalism, and cultural theory."
lang: "en"

hide_title: false
post_footer: false

icons: false
